- name: "Add Mesos log rotation"
  template:
    src: mesos.logrotate.j2
    dest: /etc/logrotate.d/mesos
    owner: root
    group: root
    mode: 0544
  become: true

- name: "Install a .deb package from the internet."
  apt:
    deb: "{{mesos_link }}"
  become: true

- name: "Create default IP for mesos master and slave"
  lineinfile:
    path: "{{ item }}"
    line: "IP=127.0.0.1"
  with_items:
    - "/etc/default/mesos-master"
    - "/etc/default/mesos-slave"
  become: true

- name: "Update log dir in config"
  lineinfile:
    path: "/etc/default/mesos"
    regexp: '^LOGS='
    line: "LOGS={{ mesos_log_dir }}"
  become: true

- name: "Copy slave config script"
  copy:
    src: "{{item}}"
    dest: "{{ mesos_home }}/{{item}}"
    owner: "{{ mesos_user }}"
    group: "{{ mesos_group }}"
    mode: "u=rwx,g=x,o=x"
  with_items:
    - set-slave-config.sh
    - set-master-config.sh
  become: true